### ISSUE TITLE
UMLS Account Migration

### ISSUE THREAD

**Issue by cannin** [PritiShaw/Analyze-MESH#3]
I tried the code, but on the https://uts.nlm.nih.gov/uts/umls/home website when I logged in accounts were migrated to external providers. Is there a way to just pass the API key?

**Comment by cannin** [comment]
Also, I think you are using this class: https://github.com/ziy/skr-webapi/blob/12a55deb21db7d822c77bb048e462c60e9fa463e/src/example/java/GenericBatchNew.java but I'm not sure how you a "processor" method. I cannot find it.

**Comment by PritiShaw** [comment]
> Also, I think you are using this class: https://github.com/ziy/skr-webapi/blob/12a55deb21db7d822c77bb048e462c60e9fa463e/src/example/java/GenericBatchNew.java but I'm not sure how you a "processor" method. I cannot find it.

You can check the code [here](https://gist.github.com/PritiShaw/d7241ee8aa5e9f19a9c62beaaee609f7#file-genericbatchnew-java-L91)  
It is similar to the `main` method in the example you gave except for the one [line](https://gist.github.com/PritiShaw/d7241ee8aa5e9f19a9c62beaaee609f7#file-genericbatchnew-java-L152) where I am sending username, password as arguments. I will check how it can be done using API key

I will share the code in a separate branch

**Comment by PritiShaw** [comment]
I am using this implementation of [GenericObject](https://github.com/ziy/skr-webapi/blob/12a55deb21db7d822c77bb048e462c60e9fa463e/src/main/java/gov/nih/nlm/nls/skr/GenericObject.java#L155) 
 
I dont see any implementation using API Key. I will search more and let you know
